// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: api/game.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Family int32

const (
	Family_FAMILY_UNSPECIFIED Family = 0
	Family_BONE               Family = 1
	Family_FIEND              Family = 2
	Family_AWAKENER           Family = 3
	Family_INSECT             Family = 4
)

// Enum value maps for Family.
var (
	Family_name = map[int32]string{
		0: "FAMILY_UNSPECIFIED",
		1: "BONE",
		2: "FIEND",
		3: "AWAKENER",
		4: "INSECT",
	}
	Family_value = map[string]int32{
		"FAMILY_UNSPECIFIED": 0,
		"BONE":               1,
		"FIEND":              2,
		"AWAKENER":           3,
		"INSECT":             4,
	}
)

func (x Family) Enum() *Family {
	p := new(Family)
	*p = x
	return p
}

func (x Family) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Family) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_proto_enumTypes[0].Descriptor()
}

func (Family) Type() protoreflect.EnumType {
	return &file_api_game_proto_enumTypes[0]
}

func (x Family) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Family.Descriptor instead.
func (Family) EnumDescriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{0}
}

type MonsterRarity int32

const (
	MonsterRarity_MONSTER_RARITY_UNSPECIFIED MonsterRarity = 0
	MonsterRarity_NORMAL                     MonsterRarity = 1
	MonsterRarity_MAGIC                      MonsterRarity = 2
	MonsterRarity_RARE                       MonsterRarity = 3
	MonsterRarity_BOSS                       MonsterRarity = 4
)

// Enum value maps for MonsterRarity.
var (
	MonsterRarity_name = map[int32]string{
		0: "MONSTER_RARITY_UNSPECIFIED",
		1: "NORMAL",
		2: "MAGIC",
		3: "RARE",
		4: "BOSS",
	}
	MonsterRarity_value = map[string]int32{
		"MONSTER_RARITY_UNSPECIFIED": 0,
		"NORMAL":                     1,
		"MAGIC":                      2,
		"RARE":                       3,
		"BOSS":                       4,
	}
)

func (x MonsterRarity) Enum() *MonsterRarity {
	p := new(MonsterRarity)
	*p = x
	return p
}

func (x MonsterRarity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonsterRarity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_proto_enumTypes[1].Descriptor()
}

func (MonsterRarity) Type() protoreflect.EnumType {
	return &file_api_game_proto_enumTypes[1]
}

func (x MonsterRarity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonsterRarity.Descriptor instead.
func (MonsterRarity) EnumDescriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{1}
}

type PotionRarity int32

const (
	PotionRarity_POTION_RARITY_UNSPECIFIED PotionRarity = 0
	PotionRarity_WHITE                     PotionRarity = 1
	PotionRarity_BLUE                      PotionRarity = 2
	PotionRarity_GOLD                      PotionRarity = 3
	PotionRarity_RED                       PotionRarity = 4
)

// Enum value maps for PotionRarity.
var (
	PotionRarity_name = map[int32]string{
		0: "POTION_RARITY_UNSPECIFIED",
		1: "WHITE",
		2: "BLUE",
		3: "GOLD",
		4: "RED",
	}
	PotionRarity_value = map[string]int32{
		"POTION_RARITY_UNSPECIFIED": 0,
		"WHITE":                     1,
		"BLUE":                      2,
		"GOLD":                      3,
		"RED":                       4,
	}
)

func (x PotionRarity) Enum() *PotionRarity {
	p := new(PotionRarity)
	*p = x
	return p
}

func (x PotionRarity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PotionRarity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_proto_enumTypes[2].Descriptor()
}

func (PotionRarity) Type() protoreflect.EnumType {
	return &file_api_game_proto_enumTypes[2]
}

func (x PotionRarity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PotionRarity.Descriptor instead.
func (PotionRarity) EnumDescriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{2}
}

type JarColor int32

const (
	JarColor_EMPTY     JarColor = 0
	JarColor_JAR_WHITE JarColor = 1
	JarColor_PURPLE    JarColor = 2
	JarColor_JAR_RED   JarColor = 3
	JarColor_RAINBOW   JarColor = 4
)

// Enum value maps for JarColor.
var (
	JarColor_name = map[int32]string{
		0: "EMPTY",
		1: "JAR_WHITE",
		2: "PURPLE",
		3: "JAR_RED",
		4: "RAINBOW",
	}
	JarColor_value = map[string]int32{
		"EMPTY":     0,
		"JAR_WHITE": 1,
		"PURPLE":    2,
		"JAR_RED":   3,
		"RAINBOW":   4,
	}
)

func (x JarColor) Enum() *JarColor {
	p := new(JarColor)
	*p = x
	return p
}

func (x JarColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JarColor) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_proto_enumTypes[3].Descriptor()
}

func (JarColor) Type() protoreflect.EnumType {
	return &file_api_game_proto_enumTypes[3]
}

func (x JarColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JarColor.Descriptor instead.
func (JarColor) EnumDescriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{3}
}

type CardKind int32

const (
	CardKind_CARD_KIND_UNSPECIFIED CardKind = 0
	CardKind_UNKNOWN               CardKind = 1
	CardKind_POTION                CardKind = 2
	CardKind_TOOL                  CardKind = 3
	CardKind_SCHEME                CardKind = 4
)

// Enum value maps for CardKind.
var (
	CardKind_name = map[int32]string{
		0: "CARD_KIND_UNSPECIFIED",
		1: "UNKNOWN",
		2: "POTION",
		3: "TOOL",
		4: "SCHEME",
	}
	CardKind_value = map[string]int32{
		"CARD_KIND_UNSPECIFIED": 0,
		"UNKNOWN":               1,
		"POTION":                2,
		"TOOL":                  3,
		"SCHEME":                4,
	}
)

func (x CardKind) Enum() *CardKind {
	p := new(CardKind)
	*p = x
	return p
}

func (x CardKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_proto_enumTypes[4].Descriptor()
}

func (CardKind) Type() protoreflect.EnumType {
	return &file_api_game_proto_enumTypes[4]
}

func (x CardKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardKind.Descriptor instead.
func (CardKind) EnumDescriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{4}
}

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PREPARING         Phase = 1
	Phase_CHOOSING          Phase = 2
	Phase_FINISHED          Phase = 3
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PREPARING",
		2: "CHOOSING",
		3: "FINISHED",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PREPARING":         1,
		"CHOOSING":          2,
		"FINISHED":          3,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_proto_enumTypes[5].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_api_game_proto_enumTypes[5]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{5}
}

type ClaimStatus int32

const (
	ClaimStatus_LOCKED  ClaimStatus = 0
	ClaimStatus_PENDING ClaimStatus = 1
	ClaimStatus_CLAIMED ClaimStatus = 2
)

// Enum value maps for ClaimStatus.
var (
	ClaimStatus_name = map[int32]string{
		0: "LOCKED",
		1: "PENDING",
		2: "CLAIMED",
	}
	ClaimStatus_value = map[string]int32{
		"LOCKED":  0,
		"PENDING": 1,
		"CLAIMED": 2,
	}
)

func (x ClaimStatus) Enum() *ClaimStatus {
	p := new(ClaimStatus)
	*p = x
	return p
}

func (x ClaimStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_proto_enumTypes[6].Descriptor()
}

func (ClaimStatus) Type() protoreflect.EnumType {
	return &file_api_game_proto_enumTypes[6]
}

func (x ClaimStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimStatus.Descriptor instead.
func (ClaimStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{6}
}

type Monster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DefinitionId  string                 `protobuf:"bytes,2,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	Family        Family                 `protobuf:"varint,3,opt,name=family,proto3,enum=vorax.v1.Family" json:"family,omitempty"`
	Rarity        MonsterRarity          `protobuf:"varint,4,opt,name=rarity,proto3,enum=vorax.v1.MonsterRarity" json:"rarity,omitempty"`
	Activity      int64                  `protobuf:"varint,5,opt,name=activity,proto3" json:"activity,omitempty"`
	Quantity      int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monster) Reset() {
	*x = Monster{}
	mi := &file_api_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monster) ProtoMessage() {}

func (x *Monster) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monster.ProtoReflect.Descriptor instead.
func (*Monster) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{0}
}

func (x *Monster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Monster) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *Monster) GetFamily() Family {
	if x != nil {
		return x.Family
	}
	return Family_FAMILY_UNSPECIFIED
}

func (x *Monster) GetRarity() MonsterRarity {
	if x != nil {
		return x.Rarity
	}
	return MonsterRarity_MONSTER_RARITY_UNSPECIFIED
}

func (x *Monster) GetActivity() int64 {
	if x != nil {
		return x.Activity
	}
	return 0
}

func (x *Monster) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Monster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Monster       *Monster               `protobuf:"bytes,2,opt,name=monster,proto3" json:"monster,omitempty"`
	Contribution  int64                  `protobuf:"varint,3,opt,name=contribution,proto3" json:"contribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_api_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Slot) GetMonster() *Monster {
	if x != nil {
		return x.Monster
	}
	return nil
}

func (x *Slot) GetContribution() int64 {
	if x != nil {
		return x.Contribution
	}
	return 0
}

type ToolClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     int64                  `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Status        ClaimStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=vorax.v1.ClaimStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolClaim) Reset() {
	*x = ToolClaim{}
	mi := &file_api_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolClaim) ProtoMessage() {}

func (x *ToolClaim) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolClaim.ProtoReflect.Descriptor instead.
func (*ToolClaim) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{2}
}

func (x *ToolClaim) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *ToolClaim) GetStatus() ClaimStatus {
	if x != nil {
		return x.Status
	}
	return ClaimStatus_LOCKED
}

type RewardState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Jars             []JarColor             `protobuf:"varint,1,rep,packed,name=jars,proto3,enum=vorax.v1.JarColor" json:"jars,omitempty"`
	DropBonusPercent int32                  `protobuf:"varint,2,opt,name=drop_bonus_percent,json=dropBonusPercent,proto3" json:"drop_bonus_percent,omitempty"`
	ToolClaims       []*ToolClaim           `protobuf:"bytes,3,rep,name=tool_claims,json=toolClaims,proto3" json:"tool_claims,omitempty"`
	NextThreshold    int64                  `protobuf:"varint,4,opt,name=next_threshold,json=nextThreshold,proto3" json:"next_threshold,omitempty"`
	NextRewardLabel  string                 `protobuf:"bytes,5,opt,name=next_reward_label,json=nextRewardLabel,proto3" json:"next_reward_label,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RewardState) Reset() {
	*x = RewardState{}
	mi := &file_api_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardState) ProtoMessage() {}

func (x *RewardState) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardState.ProtoReflect.Descriptor instead.
func (*RewardState) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{3}
}

func (x *RewardState) GetJars() []JarColor {
	if x != nil {
		return x.Jars
	}
	return nil
}

func (x *RewardState) GetDropBonusPercent() int32 {
	if x != nil {
		return x.DropBonusPercent
	}
	return 0
}

func (x *RewardState) GetToolClaims() []*ToolClaim {
	if x != nil {
		return x.ToolClaims
	}
	return nil
}

func (x *RewardState) GetNextThreshold() int64 {
	if x != nil {
		return x.NextThreshold
	}
	return 0
}

func (x *RewardState) GetNextRewardLabel() string {
	if x != nil {
		return x.NextRewardLabel
	}
	return ""
}

type Offer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind            CardKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=vorax.v1.CardKind" json:"kind,omitempty"`
	CardIds         []string               `protobuf:"bytes,3,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	Source          string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	RewardThreshold int64                  `protobuf:"varint,5,opt,name=reward_threshold,json=rewardThreshold,proto3" json:"reward_threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_api_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{4}
}

func (x *Offer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Offer) GetKind() CardKind {
	if x != nil {
		return x.Kind
	}
	return CardKind_CARD_KIND_UNSPECIFIED
}

func (x *Offer) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

func (x *Offer) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Offer) GetRewardThreshold() int64 {
	if x != nil {
		return x.RewardThreshold
	}
	return 0
}

type GameState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunId               string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Revision            uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	FormatVersion       uint32                 `protobuf:"varint,4,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	RulesVersion        string                 `protobuf:"bytes,5,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	ContentVersion      string                 `protobuf:"bytes,6,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"`
	RngVersion          string                 `protobuf:"bytes,7,opt,name=rng_version,json=rngVersion,proto3" json:"rng_version,omitempty"`
	Seed                string                 `protobuf:"bytes,8,opt,name=seed,proto3" json:"seed,omitempty"`
	Phase               Phase                  `protobuf:"varint,9,opt,name=phase,proto3,enum=vorax.v1.Phase" json:"phase,omitempty"`
	BaseCursor          int32                  `protobuf:"varint,10,opt,name=base_cursor,json=baseCursor,proto3" json:"base_cursor,omitempty"`
	CompletedTurns      int32                  `protobuf:"varint,11,opt,name=completed_turns,json=completedTurns,proto3" json:"completed_turns,omitempty"`
	Slots               []*Slot                `protobuf:"bytes,12,rep,name=slots,proto3" json:"slots,omitempty"`
	Tools               []string               `protobuf:"bytes,13,rep,name=tools,proto3" json:"tools,omitempty"`
	Offer               *Offer                 `protobuf:"bytes,14,opt,name=offer,proto3" json:"offer,omitempty"`
	PotionRefreshes     int32                  `protobuf:"varint,15,opt,name=potion_refreshes,json=potionRefreshes,proto3" json:"potion_refreshes,omitempty"`
	ToolRefreshes       int32                  `protobuf:"varint,16,opt,name=tool_refreshes,json=toolRefreshes,proto3" json:"tool_refreshes,omitempty"`
	InitialPetRefreshes int32                  `protobuf:"varint,17,opt,name=initial_pet_refreshes,json=initialPetRefreshes,proto3" json:"initial_pet_refreshes,omitempty"`
	Rewards             *RewardState           `protobuf:"bytes,18,opt,name=rewards,proto3" json:"rewards,omitempty"`
	Score               int64                  `protobuf:"varint,19,opt,name=score,proto3" json:"score,omitempty"`
	PeakScore           int64                  `protobuf:"varint,20,opt,name=peak_score,json=peakScore,proto3" json:"peak_score,omitempty"`
	InitRng             uint64                 `protobuf:"varint,21,opt,name=init_rng,json=initRng,proto3" json:"init_rng,omitempty"`
	OfferRng            uint64                 `protobuf:"varint,22,opt,name=offer_rng,json=offerRng,proto3" json:"offer_rng,omitempty"`
	EffectRng           uint64                 `protobuf:"varint,23,opt,name=effect_rng,json=effectRng,proto3" json:"effect_rng,omitempty"`
	NextMonsterId       uint64                 `protobuf:"varint,24,opt,name=next_monster_id,json=nextMonsterId,proto3" json:"next_monster_id,omitempty"`
	NextOfferId         uint64                 `protobuf:"varint,25,opt,name=next_offer_id,json=nextOfferId,proto3" json:"next_offer_id,omitempty"`
	OpeningToolFamily   Family                 `protobuf:"varint,26,opt,name=opening_tool_family,json=openingToolFamily,proto3,enum=vorax.v1.Family" json:"opening_tool_family,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_api_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameState) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GameState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GameState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GameState) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *GameState) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

func (x *GameState) GetContentVersion() string {
	if x != nil {
		return x.ContentVersion
	}
	return ""
}

func (x *GameState) GetRngVersion() string {
	if x != nil {
		return x.RngVersion
	}
	return ""
}

func (x *GameState) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *GameState) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *GameState) GetBaseCursor() int32 {
	if x != nil {
		return x.BaseCursor
	}
	return 0
}

func (x *GameState) GetCompletedTurns() int32 {
	if x != nil {
		return x.CompletedTurns
	}
	return 0
}

func (x *GameState) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *GameState) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GameState) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *GameState) GetPotionRefreshes() int32 {
	if x != nil {
		return x.PotionRefreshes
	}
	return 0
}

func (x *GameState) GetToolRefreshes() int32 {
	if x != nil {
		return x.ToolRefreshes
	}
	return 0
}

func (x *GameState) GetInitialPetRefreshes() int32 {
	if x != nil {
		return x.InitialPetRefreshes
	}
	return 0
}

func (x *GameState) GetRewards() *RewardState {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *GameState) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameState) GetPeakScore() int64 {
	if x != nil {
		return x.PeakScore
	}
	return 0
}

func (x *GameState) GetInitRng() uint64 {
	if x != nil {
		return x.InitRng
	}
	return 0
}

func (x *GameState) GetOfferRng() uint64 {
	if x != nil {
		return x.OfferRng
	}
	return 0
}

func (x *GameState) GetEffectRng() uint64 {
	if x != nil {
		return x.EffectRng
	}
	return 0
}

func (x *GameState) GetNextMonsterId() uint64 {
	if x != nil {
		return x.NextMonsterId
	}
	return 0
}

func (x *GameState) GetNextOfferId() uint64 {
	if x != nil {
		return x.NextOfferId
	}
	return 0
}

func (x *GameState) GetOpeningToolFamily() Family {
	if x != nil {
		return x.OpeningToolFamily
	}
	return Family_FAMILY_UNSPECIFIED
}

type EffectSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Activity      int64                  `protobuf:"varint,3,opt,name=activity,proto3" json:"activity,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Family        Family                 `protobuf:"varint,5,opt,name=family,proto3,enum=vorax.v1.Family" json:"family,omitempty"`
	Rarity        MonsterRarity          `protobuf:"varint,6,opt,name=rarity,proto3,enum=vorax.v1.MonsterRarity" json:"rarity,omitempty"`
	Count         int32                  `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectSpec) Reset() {
	*x = EffectSpec{}
	mi := &file_api_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectSpec) ProtoMessage() {}

func (x *EffectSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectSpec.ProtoReflect.Descriptor instead.
func (*EffectSpec) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{6}
}

func (x *EffectSpec) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *EffectSpec) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *EffectSpec) GetActivity() int64 {
	if x != nil {
		return x.Activity
	}
	return 0
}

func (x *EffectSpec) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *EffectSpec) GetFamily() Family {
	if x != nil {
		return x.Family
	}
	return Family_FAMILY_UNSPECIFIED
}

func (x *EffectSpec) GetRarity() MonsterRarity {
	if x != nil {
		return x.Rarity
	}
	return MonsterRarity_MONSTER_RARITY_UNSPECIFIED
}

func (x *EffectSpec) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CardDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Kind          CardKind               `protobuf:"varint,4,opt,name=kind,proto3,enum=vorax.v1.CardKind" json:"kind,omitempty"`
	Rarity        PotionRarity           `protobuf:"varint,5,opt,name=rarity,proto3,enum=vorax.v1.PotionRarity" json:"rarity,omitempty"`
	MinTargets    int32                  `protobuf:"varint,6,opt,name=min_targets,json=minTargets,proto3" json:"min_targets,omitempty"`
	MaxTargets    int32                  `protobuf:"varint,7,opt,name=max_targets,json=maxTargets,proto3" json:"max_targets,omitempty"`
	Handler       string                 `protobuf:"bytes,8,opt,name=handler,proto3" json:"handler,omitempty"`
	Effects       []*EffectSpec          `protobuf:"bytes,9,rep,name=effects,proto3" json:"effects,omitempty"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Trigger       string                 `protobuf:"bytes,11,opt,name=trigger,proto3" json:"trigger,omitempty"`
	CoreFamily    Family                 `protobuf:"varint,12,opt,name=core_family,json=coreFamily,proto3,enum=vorax.v1.Family" json:"core_family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardDefinition) Reset() {
	*x = CardDefinition{}
	mi := &file_api_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardDefinition) ProtoMessage() {}

func (x *CardDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardDefinition.ProtoReflect.Descriptor instead.
func (*CardDefinition) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{7}
}

func (x *CardDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CardDefinition) GetKind() CardKind {
	if x != nil {
		return x.Kind
	}
	return CardKind_CARD_KIND_UNSPECIFIED
}

func (x *CardDefinition) GetRarity() PotionRarity {
	if x != nil {
		return x.Rarity
	}
	return PotionRarity_POTION_RARITY_UNSPECIFIED
}

func (x *CardDefinition) GetMinTargets() int32 {
	if x != nil {
		return x.MinTargets
	}
	return 0
}

func (x *CardDefinition) GetMaxTargets() int32 {
	if x != nil {
		return x.MaxTargets
	}
	return 0
}

func (x *CardDefinition) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *CardDefinition) GetEffects() []*EffectSpec {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *CardDefinition) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CardDefinition) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *CardDefinition) GetCoreFamily() Family {
	if x != nil {
		return x.CoreFamily
	}
	return Family_FAMILY_UNSPECIFIED
}

type TargetSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetSet) Reset() {
	*x = TargetSet{}
	mi := &file_api_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetSet) ProtoMessage() {}

func (x *TargetSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetSet.ProtoReflect.Descriptor instead.
func (*TargetSet) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{8}
}

func (x *TargetSet) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CardView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *CardDefinition        `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	LegalTargets  []*TargetSet           `protobuf:"bytes,2,rep,name=legal_targets,json=legalTargets,proto3" json:"legal_targets,omitempty"`
	Playable      bool                   `protobuf:"varint,3,opt,name=playable,proto3" json:"playable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardView) Reset() {
	*x = CardView{}
	mi := &file_api_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardView) ProtoMessage() {}

func (x *CardView) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardView.ProtoReflect.Descriptor instead.
func (*CardView) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{9}
}

func (x *CardView) GetDefinition() *CardDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *CardView) GetLegalTargets() []*TargetSet {
	if x != nil {
		return x.LegalTargets
	}
	return nil
}

func (x *CardView) GetPlayable() bool {
	if x != nil {
		return x.Playable
	}
	return false
}

type GameView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Cards         []*CardView            `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	Tools         []*CardDefinition      `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	CanRefresh    bool                   `protobuf:"varint,4,opt,name=can_refresh,json=canRefresh,proto3" json:"can_refresh,omitempty"`
	CanSkip       bool                   `protobuf:"varint,5,opt,name=can_skip,json=canSkip,proto3" json:"can_skip,omitempty"`
	StageLabel    string                 `protobuf:"bytes,6,opt,name=stage_label,json=stageLabel,proto3" json:"stage_label,omitempty"`
	RulesNotice   string                 `protobuf:"bytes,7,opt,name=rules_notice,json=rulesNotice,proto3" json:"rules_notice,omitempty"`
	Thresholds    []int64                `protobuf:"varint,8,rep,packed,name=thresholds,proto3" json:"thresholds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameView) Reset() {
	*x = GameView{}
	mi := &file_api_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameView) ProtoMessage() {}

func (x *GameView) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameView.ProtoReflect.Descriptor instead.
func (*GameView) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{10}
}

func (x *GameView) GetState() *GameState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GameView) GetCards() []*CardView {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *GameView) GetTools() []*CardDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GameView) GetCanRefresh() bool {
	if x != nil {
		return x.CanRefresh
	}
	return false
}

func (x *GameView) GetCanSkip() bool {
	if x != nil {
		return x.CanSkip
	}
	return false
}

func (x *GameView) GetStageLabel() string {
	if x != nil {
		return x.StageLabel
	}
	return ""
}

func (x *GameView) GetRulesNotice() string {
	if x != nil {
		return x.RulesNotice
	}
	return ""
}

func (x *GameView) GetThresholds() []int64 {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

type SlotSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Monster       *Monster               `protobuf:"bytes,2,opt,name=monster,proto3" json:"monster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotSnapshot) Reset() {
	*x = SlotSnapshot{}
	mi := &file_api_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotSnapshot) ProtoMessage() {}

func (x *SlotSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotSnapshot.ProtoReflect.Descriptor instead.
func (*SlotSnapshot) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{11}
}

func (x *SlotSnapshot) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SlotSnapshot) GetMonster() *Monster {
	if x != nil {
		return x.Monster
	}
	return nil
}

type GameEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sequence       uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ParentSequence uint64                 `protobuf:"varint,2,opt,name=parent_sequence,json=parentSequence,proto3" json:"parent_sequence,omitempty"`
	Kind           string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Source         string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	TargetIds      []string               `protobuf:"bytes,5,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ActivityDelta  int64                  `protobuf:"varint,7,opt,name=activity_delta,json=activityDelta,proto3" json:"activity_delta,omitempty"`
	QuantityDelta  int64                  `protobuf:"varint,8,opt,name=quantity_delta,json=quantityDelta,proto3" json:"quantity_delta,omitempty"`
	SlotsAfter     []*SlotSnapshot        `protobuf:"bytes,9,rep,name=slots_after,json=slotsAfter,proto3" json:"slots_after,omitempty"`
	SourceName     string                 `protobuf:"bytes,10,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_api_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{12}
}

func (x *GameEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GameEvent) GetParentSequence() uint64 {
	if x != nil {
		return x.ParentSequence
	}
	return 0
}

func (x *GameEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GameEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GameEvent) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *GameEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameEvent) GetActivityDelta() int64 {
	if x != nil {
		return x.ActivityDelta
	}
	return 0
}

func (x *GameEvent) GetQuantityDelta() int64 {
	if x != nil {
		return x.QuantityDelta
	}
	return 0
}

func (x *GameEvent) GetSlotsAfter() []*SlotSnapshot {
	if x != nil {
		return x.SlotsAfter
	}
	return nil
}

func (x *GameEvent) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	OfferId       string                 `protobuf:"bytes,2,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	TargetIds     []string               `protobuf:"bytes,4,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{13}
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *Command) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Command) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type CreateRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PetRefreshes   int32                  `protobuf:"varint,2,opt,name=pet_refreshes,json=petRefreshes,proto3" json:"pet_refreshes,omitempty"`
	Seed           string                 `protobuf:"bytes,3,opt,name=seed,proto3" json:"seed,omitempty"`
	RequestId      string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RulesVersion   string                 `protobuf:"bytes,5,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	ContentVersion string                 `protobuf:"bytes,6,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"`
	RngVersion     string                 `protobuf:"bytes,7,opt,name=rng_version,json=rngVersion,proto3" json:"rng_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRunRequest) Reset() {
	*x = CreateRunRequest{}
	mi := &file_api_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunRequest) ProtoMessage() {}

func (x *CreateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunRequest.ProtoReflect.Descriptor instead.
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRunRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRunRequest) GetPetRefreshes() int32 {
	if x != nil {
		return x.PetRefreshes
	}
	return 0
}

func (x *CreateRunRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *CreateRunRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateRunRequest) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

func (x *CreateRunRequest) GetContentVersion() string {
	if x != nil {
		return x.ContentVersion
	}
	return ""
}

func (x *CreateRunRequest) GetRngVersion() string {
	if x != nil {
		return x.RngVersion
	}
	return ""
}

type CommandRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StateToken       string                 `protobuf:"bytes,1,opt,name=state_token,json=stateToken,proto3" json:"state_token,omitempty"`
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Command          *Command               `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_api_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{15}
}

func (x *CommandRequest) GetStateToken() string {
	if x != nil {
		return x.StateToken
	}
	return ""
}

func (x *CommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *CommandRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateToken    string                 `protobuf:"bytes,1,opt,name=state_token,json=stateToken,proto3" json:"state_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_api_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{16}
}

func (x *RestoreRequest) GetStateToken() string {
	if x != nil {
		return x.StateToken
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateToken    string                 `protobuf:"bytes,1,opt,name=state_token,json=stateToken,proto3" json:"state_token,omitempty"`
	View          *GameView              `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	Events        []*GameEvent           `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	GameplayHash  string                 `protobuf:"bytes,5,opt,name=gameplay_hash,json=gameplayHash,proto3" json:"gameplay_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_api_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{17}
}

func (x *RunResponse) GetStateToken() string {
	if x != nil {
		return x.StateToken
	}
	return ""
}

func (x *RunResponse) GetView() *GameView {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *RunResponse) GetEvents() []*GameEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *RunResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RunResponse) GetGameplayHash() string {
	if x != nil {
		return x.GameplayHash
	}
	return ""
}

type ReplayRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Seed                 string                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	RulesVersion         string                 `protobuf:"bytes,2,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	ContentVersion       string                 `protobuf:"bytes,3,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"`
	RngVersion           string                 `protobuf:"bytes,4,opt,name=rng_version,json=rngVersion,proto3" json:"rng_version,omitempty"`
	PetRefreshes         int32                  `protobuf:"varint,5,opt,name=pet_refreshes,json=petRefreshes,proto3" json:"pet_refreshes,omitempty"`
	Commands             []*Command             `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	ExpectedGameplayHash string                 `protobuf:"bytes,7,opt,name=expected_gameplay_hash,json=expectedGameplayHash,proto3" json:"expected_gameplay_hash,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_api_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{18}
}

func (x *ReplayRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *ReplayRequest) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

func (x *ReplayRequest) GetContentVersion() string {
	if x != nil {
		return x.ContentVersion
	}
	return ""
}

func (x *ReplayRequest) GetRngVersion() string {
	if x != nil {
		return x.RngVersion
	}
	return ""
}

func (x *ReplayRequest) GetPetRefreshes() int32 {
	if x != nil {
		return x.PetRefreshes
	}
	return 0
}

func (x *ReplayRequest) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ReplayRequest) GetExpectedGameplayHash() string {
	if x != nil {
		return x.ExpectedGameplayHash
	}
	return ""
}

type ReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	GameplayHash  string                 `protobuf:"bytes,2,opt,name=gameplay_hash,json=gameplayHash,proto3" json:"gameplay_hash,omitempty"`
	View          *GameView              `protobuf:"bytes,3,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayResponse) Reset() {
	*x = ReplayResponse{}
	mi := &file_api_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResponse) ProtoMessage() {}

func (x *ReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResponse.ProtoReflect.Descriptor instead.
func (*ReplayResponse) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{19}
}

func (x *ReplayResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *ReplayResponse) GetGameplayHash() string {
	if x != nil {
		return x.GameplayHash
	}
	return ""
}

func (x *ReplayResponse) GetView() *GameView {
	if x != nil {
		return x.View
	}
	return nil
}

type APIError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIError) Reset() {
	*x = APIError{}
	mi := &file_api_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIError) ProtoMessage() {}

func (x *APIError) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIError.ProtoReflect.Descriptor instead.
func (*APIError) Descriptor() ([]byte, []int) {
	return file_api_game_proto_rawDescGZIP(), []int{20}
}

func (x *APIError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *APIError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_game_proto protoreflect.FileDescriptor

const file_api_game_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/game.proto\x12\bvorax.v1\"\xe5\x01\n" +
	"\aMonster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdefinition_id\x18\x02 \x01(\tR\fdefinitionId\x12(\n" +
	"\x06family\x18\x03 \x01(\x0e2\x10.vorax.v1.FamilyR\x06family\x12/\n" +
	"\x06rarity\x18\x04 \x01(\x0e2\x17.vorax.v1.MonsterRarityR\x06rarity\x12\x1a\n" +
	"\bactivity\x18\x05 \x01(\x03R\bactivity\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"m\n" +
	"\x04Slot\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12+\n" +
	"\amonster\x18\x02 \x01(\v2\x11.vorax.v1.MonsterR\amonster\x12\"\n" +
	"\fcontribution\x18\x03 \x01(\x03R\fcontribution\"X\n" +
	"\tToolClaim\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x03R\tthreshold\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.vorax.v1.ClaimStatusR\x06status\"\xec\x01\n" +
	"\vRewardState\x12&\n" +
	"\x04jars\x18\x01 \x03(\x0e2\x12.vorax.v1.JarColorR\x04jars\x12,\n" +
	"\x12drop_bonus_percent\x18\x02 \x01(\x05R\x10dropBonusPercent\x124\n" +
	"\vtool_claims\x18\x03 \x03(\v2\x13.vorax.v1.ToolClaimR\n" +
	"toolClaims\x12%\n" +
	"\x0enext_threshold\x18\x04 \x01(\x03R\rnextThreshold\x12*\n" +
	"\x11next_reward_label\x18\x05 \x01(\tR\x0fnextRewardLabel\"\x9d\x01\n" +
	"\x05Offer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.vorax.v1.CardKindR\x04kind\x12\x19\n" +
	"\bcard_ids\x18\x03 \x03(\tR\acardIds\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12)\n" +
	"\x10reward_threshold\x18\x05 \x01(\x03R\x0frewardThreshold\"\xa6\a\n" +
	"\tGameState\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12%\n" +
	"\x0eformat_version\x18\x04 \x01(\rR\rformatVersion\x12#\n" +
	"\rrules_version\x18\x05 \x01(\tR\frulesVersion\x12'\n" +
	"\x0fcontent_version\x18\x06 \x01(\tR\x0econtentVersion\x12\x1f\n" +
	"\vrng_version\x18\a \x01(\tR\n" +
	"rngVersion\x12\x12\n" +
	"\x04seed\x18\b \x01(\tR\x04seed\x12%\n" +
	"\x05phase\x18\t \x01(\x0e2\x0f.vorax.v1.PhaseR\x05phase\x12\x1f\n" +
	"\vbase_cursor\x18\n" +
	" \x01(\x05R\n" +
	"baseCursor\x12'\n" +
	"\x0fcompleted_turns\x18\v \x01(\x05R\x0ecompletedTurns\x12$\n" +
	"\x05slots\x18\f \x03(\v2\x0e.vorax.v1.SlotR\x05slots\x12\x14\n" +
	"\x05tools\x18\r \x03(\tR\x05tools\x12%\n" +
	"\x05offer\x18\x0e \x01(\v2\x0f.vorax.v1.OfferR\x05offer\x12)\n" +
	"\x10potion_refreshes\x18\x0f \x01(\x05R\x0fpotionRefreshes\x12%\n" +
	"\x0etool_refreshes\x18\x10 \x01(\x05R\rtoolRefreshes\x122\n" +
	"\x15initial_pet_refreshes\x18\x11 \x01(\x05R\x13initialPetRefreshes\x12/\n" +
	"\arewards\x18\x12 \x01(\v2\x15.vorax.v1.RewardStateR\arewards\x12\x14\n" +
	"\x05score\x18\x13 \x01(\x03R\x05score\x12\x1d\n" +
	"\n" +
	"peak_score\x18\x14 \x01(\x03R\tpeakScore\x12\x19\n" +
	"\binit_rng\x18\x15 \x01(\x04R\ainitRng\x12\x1b\n" +
	"\toffer_rng\x18\x16 \x01(\x04R\bofferRng\x12\x1d\n" +
	"\n" +
	"effect_rng\x18\x17 \x01(\x04R\teffectRng\x12&\n" +
	"\x0fnext_monster_id\x18\x18 \x01(\x04R\rnextMonsterId\x12\"\n" +
	"\rnext_offer_id\x18\x19 \x01(\x04R\vnextOfferId\x12@\n" +
	"\x13opening_tool_family\x18\x1a \x01(\x0e2\x10.vorax.v1.FamilyR\x11openingToolFamily\"\xe1\x01\n" +
	"\n" +
	"EffectSpec\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x1a\n" +
	"\bactivity\x18\x03 \x01(\x03R\bactivity\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12(\n" +
	"\x06family\x18\x05 \x01(\x0e2\x10.vorax.v1.FamilyR\x06family\x12/\n" +
	"\x06rarity\x18\x06 \x01(\x0e2\x17.vorax.v1.MonsterRarityR\x06rarity\x12\x14\n" +
	"\x05count\x18\a \x01(\x05R\x05count\"\xa1\x03\n" +
	"\x0eCardDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x12.vorax.v1.CardKindR\x04kind\x12.\n" +
	"\x06rarity\x18\x05 \x01(\x0e2\x16.vorax.v1.PotionRarityR\x06rarity\x12\x1f\n" +
	"\vmin_targets\x18\x06 \x01(\x05R\n" +
	"minTargets\x12\x1f\n" +
	"\vmax_targets\x18\a \x01(\x05R\n" +
	"maxTargets\x12\x18\n" +
	"\ahandler\x18\b \x01(\tR\ahandler\x12.\n" +
	"\aeffects\x18\t \x03(\v2\x14.vorax.v1.EffectSpecR\aeffects\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12\x18\n" +
	"\atrigger\x18\v \x01(\tR\atrigger\x121\n" +
	"\vcore_family\x18\f \x01(\x0e2\x10.vorax.v1.FamilyR\n" +
	"coreFamily\"\x1d\n" +
	"\tTargetSet\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x9a\x01\n" +
	"\bCardView\x128\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x18.vorax.v1.CardDefinitionR\n" +
	"definition\x128\n" +
	"\rlegal_targets\x18\x02 \x03(\v2\x13.vorax.v1.TargetSetR\flegalTargets\x12\x1a\n" +
	"\bplayable\x18\x03 \x01(\bR\bplayable\"\xaf\x02\n" +
	"\bGameView\x12)\n" +
	"\x05state\x18\x01 \x01(\v2\x13.vorax.v1.GameStateR\x05state\x12(\n" +
	"\x05cards\x18\x02 \x03(\v2\x12.vorax.v1.CardViewR\x05cards\x12.\n" +
	"\x05tools\x18\x03 \x03(\v2\x18.vorax.v1.CardDefinitionR\x05tools\x12\x1f\n" +
	"\vcan_refresh\x18\x04 \x01(\bR\n" +
	"canRefresh\x12\x19\n" +
	"\bcan_skip\x18\x05 \x01(\bR\acanSkip\x12\x1f\n" +
	"\vstage_label\x18\x06 \x01(\tR\n" +
	"stageLabel\x12!\n" +
	"\frules_notice\x18\a \x01(\tR\vrulesNotice\x12\x1e\n" +
	"\n" +
	"thresholds\x18\b \x03(\x03R\n" +
	"thresholds\"Q\n" +
	"\fSlotSnapshot\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12+\n" +
	"\amonster\x18\x02 \x01(\v2\x11.vorax.v1.MonsterR\amonster\"\xdd\x02\n" +
	"\tGameEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12'\n" +
	"\x0fparent_sequence\x18\x02 \x01(\x04R\x0eparentSequence\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x05 \x03(\tR\ttargetIds\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12%\n" +
	"\x0eactivity_delta\x18\a \x01(\x03R\ractivityDelta\x12%\n" +
	"\x0equantity_delta\x18\b \x01(\x03R\rquantityDelta\x127\n" +
	"\vslots_after\x18\t \x03(\v2\x16.vorax.v1.SlotSnapshotR\n" +
	"slotsAfter\x12\x1f\n" +
	"\vsource_name\x18\n" +
	" \x01(\tR\n" +
	"sourceName\"p\n" +
	"\aCommand\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\boffer_id\x18\x02 \x01(\tR\aofferId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x04 \x03(\tR\ttargetIds\"\xf2\x01\n" +
	"\x10CreateRunRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rpet_refreshes\x18\x02 \x01(\x05R\fpetRefreshes\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\tR\x04seed\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12#\n" +
	"\rrules_version\x18\x05 \x01(\tR\frulesVersion\x12'\n" +
	"\x0fcontent_version\x18\x06 \x01(\tR\x0econtentVersion\x12\x1f\n" +
	"\vrng_version\x18\a \x01(\tR\n" +
	"rngVersion\"\xaa\x01\n" +
	"\x0eCommandRequest\x12\x1f\n" +
	"\vstate_token\x18\x01 \x01(\tR\n" +
	"stateToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\x12+\n" +
	"\acommand\x18\x04 \x01(\v2\x11.vorax.v1.CommandR\acommand\"1\n" +
	"\x0eRestoreRequest\x12\x1f\n" +
	"\vstate_token\x18\x01 \x01(\tR\n" +
	"stateToken\"\xc7\x01\n" +
	"\vRunResponse\x12\x1f\n" +
	"\vstate_token\x18\x01 \x01(\tR\n" +
	"stateToken\x12&\n" +
	"\x04view\x18\x02 \x01(\v2\x12.vorax.v1.GameViewR\x04view\x12+\n" +
	"\x06events\x18\x03 \x03(\v2\x13.vorax.v1.GameEventR\x06events\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12#\n" +
	"\rgameplay_hash\x18\x05 \x01(\tR\fgameplayHash\"\x9c\x02\n" +
	"\rReplayRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\tR\x04seed\x12#\n" +
	"\rrules_version\x18\x02 \x01(\tR\frulesVersion\x12'\n" +
	"\x0fcontent_version\x18\x03 \x01(\tR\x0econtentVersion\x12\x1f\n" +
	"\vrng_version\x18\x04 \x01(\tR\n" +
	"rngVersion\x12#\n" +
	"\rpet_refreshes\x18\x05 \x01(\x05R\fpetRefreshes\x12-\n" +
	"\bcommands\x18\x06 \x03(\v2\x11.vorax.v1.CommandR\bcommands\x124\n" +
	"\x16expected_gameplay_hash\x18\a \x01(\tR\x14expectedGameplayHash\"y\n" +
	"\x0eReplayResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12#\n" +
	"\rgameplay_hash\x18\x02 \x01(\tR\fgameplayHash\x12&\n" +
	"\x04view\x18\x03 \x01(\v2\x12.vorax.v1.GameViewR\x04view\"8\n" +
	"\bAPIError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*O\n" +
	"\x06Family\x12\x16\n" +
	"\x12FAMILY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04BONE\x10\x01\x12\t\n" +
	"\x05FIEND\x10\x02\x12\f\n" +
	"\bAWAKENER\x10\x03\x12\n" +
	"\n" +
	"\x06INSECT\x10\x04*Z\n" +
	"\rMonsterRarity\x12\x1e\n" +
	"\x1aMONSTER_RARITY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\t\n" +
	"\x05MAGIC\x10\x02\x12\b\n" +
	"\x04RARE\x10\x03\x12\b\n" +
	"\x04BOSS\x10\x04*U\n" +
	"\fPotionRarity\x12\x1d\n" +
	"\x19POTION_RARITY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05WHITE\x10\x01\x12\b\n" +
	"\x04BLUE\x10\x02\x12\b\n" +
	"\x04GOLD\x10\x03\x12\a\n" +
	"\x03RED\x10\x04*J\n" +
	"\bJarColor\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\r\n" +
	"\tJAR_WHITE\x10\x01\x12\n" +
	"\n" +
	"\x06PURPLE\x10\x02\x12\v\n" +
	"\aJAR_RED\x10\x03\x12\v\n" +
	"\aRAINBOW\x10\x04*T\n" +
	"\bCardKind\x12\x19\n" +
	"\x15CARD_KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\n" +
	"\n" +
	"\x06POTION\x10\x02\x12\b\n" +
	"\x04TOOL\x10\x03\x12\n" +
	"\n" +
	"\x06SCHEME\x10\x04*I\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPREPARING\x10\x01\x12\f\n" +
	"\bCHOOSING\x10\x02\x12\f\n" +
	"\bFINISHED\x10\x03*3\n" +
	"\vClaimStatus\x12\n" +
	"\n" +
	"\x06LOCKED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aCLAIMED\x10\x02B\"Z vorax/internal/protocol;protocolb\x06proto3"

var (
	file_api_game_proto_rawDescOnce sync.Once
	file_api_game_proto_rawDescData []byte
)

func file_api_game_proto_rawDescGZIP() []byte {
	file_api_game_proto_rawDescOnce.Do(func() {
		file_api_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_game_proto_rawDesc), len(file_api_game_proto_rawDesc)))
	})
	return file_api_game_proto_rawDescData
}

var file_api_game_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_api_game_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_game_proto_goTypes = []any{
	(Family)(0),              // 0: vorax.v1.Family
	(MonsterRarity)(0),       // 1: vorax.v1.MonsterRarity
	(PotionRarity)(0),        // 2: vorax.v1.PotionRarity
	(JarColor)(0),            // 3: vorax.v1.JarColor
	(CardKind)(0),            // 4: vorax.v1.CardKind
	(Phase)(0),               // 5: vorax.v1.Phase
	(ClaimStatus)(0),         // 6: vorax.v1.ClaimStatus
	(*Monster)(nil),          // 7: vorax.v1.Monster
	(*Slot)(nil),             // 8: vorax.v1.Slot
	(*ToolClaim)(nil),        // 9: vorax.v1.ToolClaim
	(*RewardState)(nil),      // 10: vorax.v1.RewardState
	(*Offer)(nil),            // 11: vorax.v1.Offer
	(*GameState)(nil),        // 12: vorax.v1.GameState
	(*EffectSpec)(nil),       // 13: vorax.v1.EffectSpec
	(*CardDefinition)(nil),   // 14: vorax.v1.CardDefinition
	(*TargetSet)(nil),        // 15: vorax.v1.TargetSet
	(*CardView)(nil),         // 16: vorax.v1.CardView
	(*GameView)(nil),         // 17: vorax.v1.GameView
	(*SlotSnapshot)(nil),     // 18: vorax.v1.SlotSnapshot
	(*GameEvent)(nil),        // 19: vorax.v1.GameEvent
	(*Command)(nil),          // 20: vorax.v1.Command
	(*CreateRunRequest)(nil), // 21: vorax.v1.CreateRunRequest
	(*CommandRequest)(nil),   // 22: vorax.v1.CommandRequest
	(*RestoreRequest)(nil),   // 23: vorax.v1.RestoreRequest
	(*RunResponse)(nil),      // 24: vorax.v1.RunResponse
	(*ReplayRequest)(nil),    // 25: vorax.v1.ReplayRequest
	(*ReplayResponse)(nil),   // 26: vorax.v1.ReplayResponse
	(*APIError)(nil),         // 27: vorax.v1.APIError
}
var file_api_game_proto_depIdxs = []int32{
	0,  // 0: vorax.v1.Monster.family:type_name -> vorax.v1.Family
	1,  // 1: vorax.v1.Monster.rarity:type_name -> vorax.v1.MonsterRarity
	7,  // 2: vorax.v1.Slot.monster:type_name -> vorax.v1.Monster
	6,  // 3: vorax.v1.ToolClaim.status:type_name -> vorax.v1.ClaimStatus
	3,  // 4: vorax.v1.RewardState.jars:type_name -> vorax.v1.JarColor
	9,  // 5: vorax.v1.RewardState.tool_claims:type_name -> vorax.v1.ToolClaim
	4,  // 6: vorax.v1.Offer.kind:type_name -> vorax.v1.CardKind
	5,  // 7: vorax.v1.GameState.phase:type_name -> vorax.v1.Phase
	8,  // 8: vorax.v1.GameState.slots:type_name -> vorax.v1.Slot
	11, // 9: vorax.v1.GameState.offer:type_name -> vorax.v1.Offer
	10, // 10: vorax.v1.GameState.rewards:type_name -> vorax.v1.RewardState
	0,  // 11: vorax.v1.GameState.opening_tool_family:type_name -> vorax.v1.Family
	0,  // 12: vorax.v1.EffectSpec.family:type_name -> vorax.v1.Family
	1,  // 13: vorax.v1.EffectSpec.rarity:type_name -> vorax.v1.MonsterRarity
	4,  // 14: vorax.v1.CardDefinition.kind:type_name -> vorax.v1.CardKind
	2,  // 15: vorax.v1.CardDefinition.rarity:type_name -> vorax.v1.PotionRarity
	13, // 16: vorax.v1.CardDefinition.effects:type_name -> vorax.v1.EffectSpec
	0,  // 17: vorax.v1.CardDefinition.core_family:type_name -> vorax.v1.Family
	14, // 18: vorax.v1.CardView.definition:type_name -> vorax.v1.CardDefinition
	15, // 19: vorax.v1.CardView.legal_targets:type_name -> vorax.v1.TargetSet
	12, // 20: vorax.v1.GameView.state:type_name -> vorax.v1.GameState
	16, // 21: vorax.v1.GameView.cards:type_name -> vorax.v1.CardView
	14, // 22: vorax.v1.GameView.tools:type_name -> vorax.v1.CardDefinition
	7,  // 23: vorax.v1.SlotSnapshot.monster:type_name -> vorax.v1.Monster
	18, // 24: vorax.v1.GameEvent.slots_after:type_name -> vorax.v1.SlotSnapshot
	20, // 25: vorax.v1.CommandRequest.command:type_name -> vorax.v1.Command
	17, // 26: vorax.v1.RunResponse.view:type_name -> vorax.v1.GameView
	19, // 27: vorax.v1.RunResponse.events:type_name -> vorax.v1.GameEvent
	20, // 28: vorax.v1.ReplayRequest.commands:type_name -> vorax.v1.Command
	17, // 29: vorax.v1.ReplayResponse.view:type_name -> vorax.v1.GameView
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_api_game_proto_init() }
func file_api_game_proto_init() {
	if File_api_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_game_proto_rawDesc), len(file_api_game_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_game_proto_goTypes,
		DependencyIndexes: file_api_game_proto_depIdxs,
		EnumInfos:         file_api_game_proto_enumTypes,
		MessageInfos:      file_api_game_proto_msgTypes,
	}.Build()
	File_api_game_proto = out.File
	file_api_game_proto_goTypes = nil
	file_api_game_proto_depIdxs = nil
}
