// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: api/training.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainingAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	TargetSlots   []int32                `protobuf:"varint,3,rep,packed,name=target_slots,json=targetSlots,proto3" json:"target_slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingAction) Reset() {
	*x = TrainingAction{}
	mi := &file_api_training_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingAction) ProtoMessage() {}

func (x *TrainingAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingAction.ProtoReflect.Descriptor instead.
func (*TrainingAction) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{0}
}

func (x *TrainingAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TrainingAction) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *TrainingAction) GetTargetSlots() []int32 {
	if x != nil {
		return x.TargetSlots
	}
	return nil
}

type TrainingSlotObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefinitionId  string                 `protobuf:"bytes,1,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Family        int32                  `protobuf:"varint,4,opt,name=family,proto3" json:"family,omitempty"`
	Rarity        int32                  `protobuf:"varint,5,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Activity      int64                  `protobuf:"varint,6,opt,name=activity,proto3" json:"activity,omitempty"`
	Quantity      int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingSlotObservation) Reset() {
	*x = TrainingSlotObservation{}
	mi := &file_api_training_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingSlotObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSlotObservation) ProtoMessage() {}

func (x *TrainingSlotObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSlotObservation.ProtoReflect.Descriptor instead.
func (*TrainingSlotObservation) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{1}
}

func (x *TrainingSlotObservation) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *TrainingSlotObservation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingSlotObservation) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TrainingSlotObservation) GetFamily() int32 {
	if x != nil {
		return x.Family
	}
	return 0
}

func (x *TrainingSlotObservation) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *TrainingSlotObservation) GetActivity() int64 {
	if x != nil {
		return x.Activity
	}
	return 0
}

func (x *TrainingSlotObservation) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type TrainingOfferObservation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	RewardThreshold int64                  `protobuf:"varint,2,opt,name=reward_threshold,json=rewardThreshold,proto3" json:"reward_threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainingOfferObservation) Reset() {
	*x = TrainingOfferObservation{}
	mi := &file_api_training_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingOfferObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingOfferObservation) ProtoMessage() {}

func (x *TrainingOfferObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingOfferObservation.ProtoReflect.Descriptor instead.
func (*TrainingOfferObservation) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{2}
}

func (x *TrainingOfferObservation) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *TrainingOfferObservation) GetRewardThreshold() int64 {
	if x != nil {
		return x.RewardThreshold
	}
	return 0
}

type TrainingTargetSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []int32                `protobuf:"varint,1,rep,packed,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingTargetSet) Reset() {
	*x = TrainingTargetSet{}
	mi := &file_api_training_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingTargetSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingTargetSet) ProtoMessage() {}

func (x *TrainingTargetSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingTargetSet.ProtoReflect.Descriptor instead.
func (*TrainingTargetSet) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{3}
}

func (x *TrainingTargetSet) GetSlots() []int32 {
	if x != nil {
		return x.Slots
	}
	return nil
}

type TrainingCardObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Kind          int32                  `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Rarity        int32                  `protobuf:"varint,5,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Playable      bool                   `protobuf:"varint,6,opt,name=playable,proto3" json:"playable,omitempty"`
	TargetSets    []*TrainingTargetSet   `protobuf:"bytes,7,rep,name=target_sets,json=targetSets,proto3" json:"target_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingCardObservation) Reset() {
	*x = TrainingCardObservation{}
	mi := &file_api_training_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingCardObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingCardObservation) ProtoMessage() {}

func (x *TrainingCardObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingCardObservation.ProtoReflect.Descriptor instead.
func (*TrainingCardObservation) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{4}
}

func (x *TrainingCardObservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingCardObservation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingCardObservation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TrainingCardObservation) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *TrainingCardObservation) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *TrainingCardObservation) GetPlayable() bool {
	if x != nil {
		return x.Playable
	}
	return false
}

func (x *TrainingCardObservation) GetTargetSets() []*TrainingTargetSet {
	if x != nil {
		return x.TargetSets
	}
	return nil
}

type TrainingClaimObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     int64                  `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingClaimObservation) Reset() {
	*x = TrainingClaimObservation{}
	mi := &file_api_training_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingClaimObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingClaimObservation) ProtoMessage() {}

func (x *TrainingClaimObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingClaimObservation.ProtoReflect.Descriptor instead.
func (*TrainingClaimObservation) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{5}
}

func (x *TrainingClaimObservation) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *TrainingClaimObservation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TrainingRewardObservation struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	Jars             []int32                     `protobuf:"varint,1,rep,packed,name=jars,proto3" json:"jars,omitempty"`
	DropBonusPercent int32                       `protobuf:"varint,2,opt,name=drop_bonus_percent,json=dropBonusPercent,proto3" json:"drop_bonus_percent,omitempty"`
	NextThreshold    int64                       `protobuf:"varint,3,opt,name=next_threshold,json=nextThreshold,proto3" json:"next_threshold,omitempty"`
	NextRewardLabel  string                      `protobuf:"bytes,4,opt,name=next_reward_label,json=nextRewardLabel,proto3" json:"next_reward_label,omitempty"`
	ToolClaims       []*TrainingClaimObservation `protobuf:"bytes,5,rep,name=tool_claims,json=toolClaims,proto3" json:"tool_claims,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrainingRewardObservation) Reset() {
	*x = TrainingRewardObservation{}
	mi := &file_api_training_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingRewardObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingRewardObservation) ProtoMessage() {}

func (x *TrainingRewardObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingRewardObservation.ProtoReflect.Descriptor instead.
func (*TrainingRewardObservation) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{6}
}

func (x *TrainingRewardObservation) GetJars() []int32 {
	if x != nil {
		return x.Jars
	}
	return nil
}

func (x *TrainingRewardObservation) GetDropBonusPercent() int32 {
	if x != nil {
		return x.DropBonusPercent
	}
	return 0
}

func (x *TrainingRewardObservation) GetNextThreshold() int64 {
	if x != nil {
		return x.NextThreshold
	}
	return 0
}

func (x *TrainingRewardObservation) GetNextRewardLabel() string {
	if x != nil {
		return x.NextRewardLabel
	}
	return ""
}

func (x *TrainingRewardObservation) GetToolClaims() []*TrainingClaimObservation {
	if x != nil {
		return x.ToolClaims
	}
	return nil
}

type TrainingObservation struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Phase           string                     `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	StageLabel      string                     `protobuf:"bytes,2,opt,name=stage_label,json=stageLabel,proto3" json:"stage_label,omitempty"`
	BaseCursor      int32                      `protobuf:"varint,3,opt,name=base_cursor,json=baseCursor,proto3" json:"base_cursor,omitempty"`
	CompletedTurns  int32                      `protobuf:"varint,4,opt,name=completed_turns,json=completedTurns,proto3" json:"completed_turns,omitempty"`
	Score           int64                      `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	Slots           []*TrainingSlotObservation `protobuf:"bytes,6,rep,name=slots,proto3" json:"slots,omitempty"`
	Tools           []string                   `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	ToolNames       []string                   `protobuf:"bytes,8,rep,name=tool_names,json=toolNames,proto3" json:"tool_names,omitempty"`
	Offer           *TrainingOfferObservation  `protobuf:"bytes,9,opt,name=offer,proto3" json:"offer,omitempty"`
	Cards           []*TrainingCardObservation `protobuf:"bytes,10,rep,name=cards,proto3" json:"cards,omitempty"`
	CanSkip         bool                       `protobuf:"varint,11,opt,name=can_skip,json=canSkip,proto3" json:"can_skip,omitempty"`
	CanRefresh      bool                       `protobuf:"varint,12,opt,name=can_refresh,json=canRefresh,proto3" json:"can_refresh,omitempty"`
	PotionRefreshes int32                      `protobuf:"varint,13,opt,name=potion_refreshes,json=potionRefreshes,proto3" json:"potion_refreshes,omitempty"`
	ToolRefreshes   int32                      `protobuf:"varint,14,opt,name=tool_refreshes,json=toolRefreshes,proto3" json:"tool_refreshes,omitempty"`
	Rewards         *TrainingRewardObservation `protobuf:"bytes,15,opt,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainingObservation) Reset() {
	*x = TrainingObservation{}
	mi := &file_api_training_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingObservation) ProtoMessage() {}

func (x *TrainingObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingObservation.ProtoReflect.Descriptor instead.
func (*TrainingObservation) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{7}
}

func (x *TrainingObservation) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *TrainingObservation) GetStageLabel() string {
	if x != nil {
		return x.StageLabel
	}
	return ""
}

func (x *TrainingObservation) GetBaseCursor() int32 {
	if x != nil {
		return x.BaseCursor
	}
	return 0
}

func (x *TrainingObservation) GetCompletedTurns() int32 {
	if x != nil {
		return x.CompletedTurns
	}
	return 0
}

func (x *TrainingObservation) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TrainingObservation) GetSlots() []*TrainingSlotObservation {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *TrainingObservation) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *TrainingObservation) GetToolNames() []string {
	if x != nil {
		return x.ToolNames
	}
	return nil
}

func (x *TrainingObservation) GetOffer() *TrainingOfferObservation {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *TrainingObservation) GetCards() []*TrainingCardObservation {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *TrainingObservation) GetCanSkip() bool {
	if x != nil {
		return x.CanSkip
	}
	return false
}

func (x *TrainingObservation) GetCanRefresh() bool {
	if x != nil {
		return x.CanRefresh
	}
	return false
}

func (x *TrainingObservation) GetPotionRefreshes() int32 {
	if x != nil {
		return x.PotionRefreshes
	}
	return 0
}

func (x *TrainingObservation) GetToolRefreshes() int32 {
	if x != nil {
		return x.ToolRefreshes
	}
	return 0
}

func (x *TrainingObservation) GetRewards() *TrainingRewardObservation {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// Fixed-shape integer tensors. Catalog indexes use 0 for empty/padding and
// otherwise are one-based indexes into TrainingSpec monster_ids/card_ids.
type TensorObservation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Phase                int32                  `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Progress             []int32                `protobuf:"varint,2,rep,packed,name=progress,proto3" json:"progress,omitempty"` // [base_cursor, completed_turns]
	Score                int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	SlotMonsters         []int32                `protobuf:"varint,4,rep,packed,name=slot_monsters,json=slotMonsters,proto3" json:"slot_monsters,omitempty"`       // [6]
	SlotFamilies         []int32                `protobuf:"varint,5,rep,packed,name=slot_families,json=slotFamilies,proto3" json:"slot_families,omitempty"`       // [6]
	SlotRarities         []int32                `protobuf:"varint,6,rep,packed,name=slot_rarities,json=slotRarities,proto3" json:"slot_rarities,omitempty"`       // [6]
	SlotActivities       []int64                `protobuf:"varint,7,rep,packed,name=slot_activities,json=slotActivities,proto3" json:"slot_activities,omitempty"` // [6]
	SlotQuantities       []int64                `protobuf:"varint,8,rep,packed,name=slot_quantities,json=slotQuantities,proto3" json:"slot_quantities,omitempty"` // [6]
	ToolCounts           []int32                `protobuf:"varint,9,rep,packed,name=tool_counts,json=toolCounts,proto3" json:"tool_counts,omitempty"`             // [tool_count]
	Offer                []int32                `protobuf:"varint,10,rep,packed,name=offer,proto3" json:"offer,omitempty"`                                        // [kind]
	OfferRewardThreshold int64                  `protobuf:"varint,11,opt,name=offer_reward_threshold,json=offerRewardThreshold,proto3" json:"offer_reward_threshold,omitempty"`
	CandidateCards       []int32                `protobuf:"varint,12,rep,packed,name=candidate_cards,json=candidateCards,proto3" json:"candidate_cards,omitempty"`          // [5]
	CandidatePlayable    []int32                `protobuf:"varint,13,rep,packed,name=candidate_playable,json=candidatePlayable,proto3" json:"candidate_playable,omitempty"` // [5]
	Refreshes            []int32                `protobuf:"varint,14,rep,packed,name=refreshes,proto3" json:"refreshes,omitempty"`                                          // [potion, tool]
	RewardJars           []int32                `protobuf:"varint,15,rep,packed,name=reward_jars,json=rewardJars,proto3" json:"reward_jars,omitempty"`                      // [6]
	DropBonusPercent     int32                  `protobuf:"varint,16,opt,name=drop_bonus_percent,json=dropBonusPercent,proto3" json:"drop_bonus_percent,omitempty"`
	ToolClaimStatuses    []int32                `protobuf:"varint,17,rep,packed,name=tool_claim_statuses,json=toolClaimStatuses,proto3" json:"tool_claim_statuses,omitempty"` // [2], LOCKED=0/PENDING=1/CLAIMED=2
	NextRewardThreshold  int64                  `protobuf:"varint,18,opt,name=next_reward_threshold,json=nextRewardThreshold,proto3" json:"next_reward_threshold,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TensorObservation) Reset() {
	*x = TensorObservation{}
	mi := &file_api_training_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorObservation) ProtoMessage() {}

func (x *TensorObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorObservation.ProtoReflect.Descriptor instead.
func (*TensorObservation) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{8}
}

func (x *TensorObservation) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *TensorObservation) GetProgress() []int32 {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *TensorObservation) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TensorObservation) GetSlotMonsters() []int32 {
	if x != nil {
		return x.SlotMonsters
	}
	return nil
}

func (x *TensorObservation) GetSlotFamilies() []int32 {
	if x != nil {
		return x.SlotFamilies
	}
	return nil
}

func (x *TensorObservation) GetSlotRarities() []int32 {
	if x != nil {
		return x.SlotRarities
	}
	return nil
}

func (x *TensorObservation) GetSlotActivities() []int64 {
	if x != nil {
		return x.SlotActivities
	}
	return nil
}

func (x *TensorObservation) GetSlotQuantities() []int64 {
	if x != nil {
		return x.SlotQuantities
	}
	return nil
}

func (x *TensorObservation) GetToolCounts() []int32 {
	if x != nil {
		return x.ToolCounts
	}
	return nil
}

func (x *TensorObservation) GetOffer() []int32 {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *TensorObservation) GetOfferRewardThreshold() int64 {
	if x != nil {
		return x.OfferRewardThreshold
	}
	return 0
}

func (x *TensorObservation) GetCandidateCards() []int32 {
	if x != nil {
		return x.CandidateCards
	}
	return nil
}

func (x *TensorObservation) GetCandidatePlayable() []int32 {
	if x != nil {
		return x.CandidatePlayable
	}
	return nil
}

func (x *TensorObservation) GetRefreshes() []int32 {
	if x != nil {
		return x.Refreshes
	}
	return nil
}

func (x *TensorObservation) GetRewardJars() []int32 {
	if x != nil {
		return x.RewardJars
	}
	return nil
}

func (x *TensorObservation) GetDropBonusPercent() int32 {
	if x != nil {
		return x.DropBonusPercent
	}
	return 0
}

func (x *TensorObservation) GetToolClaimStatuses() []int32 {
	if x != nil {
		return x.ToolClaimStatuses
	}
	return nil
}

func (x *TensorObservation) GetNextRewardThreshold() int64 {
	if x != nil {
		return x.NextRewardThreshold
	}
	return 0
}

type TrainingInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Score          int64                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	RulesVersion   string                 `protobuf:"bytes,2,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	ContentVersion string                 `protobuf:"bytes,3,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"`
	RngVersion     string                 `protobuf:"bytes,4,opt,name=rng_version,json=rngVersion,proto3" json:"rng_version,omitempty"`
	SpecVersion    string                 `protobuf:"bytes,5,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrainingInfo) Reset() {
	*x = TrainingInfo{}
	mi := &file_api_training_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingInfo) ProtoMessage() {}

func (x *TrainingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingInfo.ProtoReflect.Descriptor instead.
func (*TrainingInfo) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{9}
}

func (x *TrainingInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TrainingInfo) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

func (x *TrainingInfo) GetContentVersion() string {
	if x != nil {
		return x.ContentVersion
	}
	return ""
}

func (x *TrainingInfo) GetRngVersion() string {
	if x != nil {
		return x.RngVersion
	}
	return ""
}

func (x *TrainingInfo) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

type TrainingTransition struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EpisodeToken      string                 `protobuf:"bytes,1,opt,name=episode_token,json=episodeToken,proto3" json:"episode_token,omitempty"`
	Observation       *TrainingObservation   `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	TensorObservation *TensorObservation     `protobuf:"bytes,3,opt,name=tensor_observation,json=tensorObservation,proto3" json:"tensor_observation,omitempty"`
	LegalActions      []*TrainingAction      `protobuf:"bytes,4,rep,name=legal_actions,json=legalActions,proto3" json:"legal_actions,omitempty"`
	ActionMask        []int32                `protobuf:"varint,5,rep,packed,name=action_mask,json=actionMask,proto3" json:"action_mask,omitempty"`
	Reward            int64                  `protobuf:"varint,6,opt,name=reward,proto3" json:"reward,omitempty"`
	Terminated        bool                   `protobuf:"varint,7,opt,name=terminated,proto3" json:"terminated,omitempty"`
	Truncated         bool                   `protobuf:"varint,8,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Info              *TrainingInfo          `protobuf:"bytes,9,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrainingTransition) Reset() {
	*x = TrainingTransition{}
	mi := &file_api_training_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingTransition) ProtoMessage() {}

func (x *TrainingTransition) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingTransition.ProtoReflect.Descriptor instead.
func (*TrainingTransition) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{10}
}

func (x *TrainingTransition) GetEpisodeToken() string {
	if x != nil {
		return x.EpisodeToken
	}
	return ""
}

func (x *TrainingTransition) GetObservation() *TrainingObservation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *TrainingTransition) GetTensorObservation() *TensorObservation {
	if x != nil {
		return x.TensorObservation
	}
	return nil
}

func (x *TrainingTransition) GetLegalActions() []*TrainingAction {
	if x != nil {
		return x.LegalActions
	}
	return nil
}

func (x *TrainingTransition) GetActionMask() []int32 {
	if x != nil {
		return x.ActionMask
	}
	return nil
}

func (x *TrainingTransition) GetReward() int64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *TrainingTransition) GetTerminated() bool {
	if x != nil {
		return x.Terminated
	}
	return false
}

func (x *TrainingTransition) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *TrainingTransition) GetInfo() *TrainingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type TrainingActionSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Action        *TrainingAction        `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingActionSpec) Reset() {
	*x = TrainingActionSpec{}
	mi := &file_api_training_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingActionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingActionSpec) ProtoMessage() {}

func (x *TrainingActionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingActionSpec.ProtoReflect.Descriptor instead.
func (*TrainingActionSpec) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{11}
}

func (x *TrainingActionSpec) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TrainingActionSpec) GetAction() *TrainingAction {
	if x != nil {
		return x.Action
	}
	return nil
}

type TrainingTensorSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SlotCount       int32                  `protobuf:"varint,1,opt,name=slot_count,json=slotCount,proto3" json:"slot_count,omitempty"`
	CandidateCount  int32                  `protobuf:"varint,2,opt,name=candidate_count,json=candidateCount,proto3" json:"candidate_count,omitempty"`
	ToolCount       int32                  `protobuf:"varint,3,opt,name=tool_count,json=toolCount,proto3" json:"tool_count,omitempty"`
	ActionCount     int32                  `protobuf:"varint,4,opt,name=action_count,json=actionCount,proto3" json:"action_count,omitempty"`
	IntegerEncoding string                 `protobuf:"bytes,5,opt,name=integer_encoding,json=integerEncoding,proto3" json:"integer_encoding,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainingTensorSpec) Reset() {
	*x = TrainingTensorSpec{}
	mi := &file_api_training_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingTensorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingTensorSpec) ProtoMessage() {}

func (x *TrainingTensorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingTensorSpec.ProtoReflect.Descriptor instead.
func (*TrainingTensorSpec) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{12}
}

func (x *TrainingTensorSpec) GetSlotCount() int32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *TrainingTensorSpec) GetCandidateCount() int32 {
	if x != nil {
		return x.CandidateCount
	}
	return 0
}

func (x *TrainingTensorSpec) GetToolCount() int32 {
	if x != nil {
		return x.ToolCount
	}
	return 0
}

func (x *TrainingTensorSpec) GetActionCount() int32 {
	if x != nil {
		return x.ActionCount
	}
	return 0
}

func (x *TrainingTensorSpec) GetIntegerEncoding() string {
	if x != nil {
		return x.IntegerEncoding
	}
	return ""
}

type TrainingSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpecVersion    string                 `protobuf:"bytes,1,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	SpecHash       string                 `protobuf:"bytes,2,opt,name=spec_hash,json=specHash,proto3" json:"spec_hash,omitempty"`
	RulesVersion   string                 `protobuf:"bytes,3,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	ContentVersion string                 `protobuf:"bytes,4,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"`
	RngVersion     string                 `protobuf:"bytes,5,opt,name=rng_version,json=rngVersion,proto3" json:"rng_version,omitempty"`
	MonsterIds     []string               `protobuf:"bytes,6,rep,name=monster_ids,json=monsterIds,proto3" json:"monster_ids,omitempty"`
	CardIds        []string               `protobuf:"bytes,7,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	ToolIds        []string               `protobuf:"bytes,8,rep,name=tool_ids,json=toolIds,proto3" json:"tool_ids,omitempty"`
	Actions        []*TrainingActionSpec  `protobuf:"bytes,9,rep,name=actions,proto3" json:"actions,omitempty"`
	Tensor         *TrainingTensorSpec    `protobuf:"bytes,10,opt,name=tensor,proto3" json:"tensor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrainingSpec) Reset() {
	*x = TrainingSpec{}
	mi := &file_api_training_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSpec) ProtoMessage() {}

func (x *TrainingSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSpec.ProtoReflect.Descriptor instead.
func (*TrainingSpec) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{13}
}

func (x *TrainingSpec) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

func (x *TrainingSpec) GetSpecHash() string {
	if x != nil {
		return x.SpecHash
	}
	return ""
}

func (x *TrainingSpec) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

func (x *TrainingSpec) GetContentVersion() string {
	if x != nil {
		return x.ContentVersion
	}
	return ""
}

func (x *TrainingSpec) GetRngVersion() string {
	if x != nil {
		return x.RngVersion
	}
	return ""
}

func (x *TrainingSpec) GetMonsterIds() []string {
	if x != nil {
		return x.MonsterIds
	}
	return nil
}

func (x *TrainingSpec) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

func (x *TrainingSpec) GetToolIds() []string {
	if x != nil {
		return x.ToolIds
	}
	return nil
}

func (x *TrainingSpec) GetActions() []*TrainingActionSpec {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *TrainingSpec) GetTensor() *TrainingTensorSpec {
	if x != nil {
		return x.Tensor
	}
	return nil
}

type TrainingResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          string                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	PetRefreshes  int32                  `protobuf:"varint,2,opt,name=pet_refreshes,json=petRefreshes,proto3" json:"pet_refreshes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingResetRequest) Reset() {
	*x = TrainingResetRequest{}
	mi := &file_api_training_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingResetRequest) ProtoMessage() {}

func (x *TrainingResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingResetRequest.ProtoReflect.Descriptor instead.
func (*TrainingResetRequest) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{14}
}

func (x *TrainingResetRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *TrainingResetRequest) GetPetRefreshes() int32 {
	if x != nil {
		return x.PetRefreshes
	}
	return 0
}

type TrainingStepRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	EpisodeToken string                 `protobuf:"bytes,1,opt,name=episode_token,json=episodeToken,proto3" json:"episode_token,omitempty"`
	// Types that are valid to be assigned to SelectedAction:
	//
	//	*TrainingStepRequest_ActionIndex
	//	*TrainingStepRequest_Action
	SelectedAction isTrainingStepRequest_SelectedAction `protobuf_oneof:"selected_action"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrainingStepRequest) Reset() {
	*x = TrainingStepRequest{}
	mi := &file_api_training_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingStepRequest) ProtoMessage() {}

func (x *TrainingStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingStepRequest.ProtoReflect.Descriptor instead.
func (*TrainingStepRequest) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{15}
}

func (x *TrainingStepRequest) GetEpisodeToken() string {
	if x != nil {
		return x.EpisodeToken
	}
	return ""
}

func (x *TrainingStepRequest) GetSelectedAction() isTrainingStepRequest_SelectedAction {
	if x != nil {
		return x.SelectedAction
	}
	return nil
}

func (x *TrainingStepRequest) GetActionIndex() int32 {
	if x != nil {
		if x, ok := x.SelectedAction.(*TrainingStepRequest_ActionIndex); ok {
			return x.ActionIndex
		}
	}
	return 0
}

func (x *TrainingStepRequest) GetAction() *TrainingAction {
	if x != nil {
		if x, ok := x.SelectedAction.(*TrainingStepRequest_Action); ok {
			return x.Action
		}
	}
	return nil
}

type isTrainingStepRequest_SelectedAction interface {
	isTrainingStepRequest_SelectedAction()
}

type TrainingStepRequest_ActionIndex struct {
	ActionIndex int32 `protobuf:"varint,2,opt,name=action_index,json=actionIndex,proto3,oneof"`
}

type TrainingStepRequest_Action struct {
	Action *TrainingAction `protobuf:"bytes,3,opt,name=action,proto3,oneof"`
}

func (*TrainingStepRequest_ActionIndex) isTrainingStepRequest_SelectedAction() {}

func (*TrainingStepRequest_Action) isTrainingStepRequest_SelectedAction() {}

type TrainingBatchResetRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*TrainingResetRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingBatchResetRequest) Reset() {
	*x = TrainingBatchResetRequest{}
	mi := &file_api_training_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingBatchResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingBatchResetRequest) ProtoMessage() {}

func (x *TrainingBatchResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingBatchResetRequest.ProtoReflect.Descriptor instead.
func (*TrainingBatchResetRequest) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{16}
}

func (x *TrainingBatchResetRequest) GetItems() []*TrainingResetRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type TrainingBatchStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TrainingStepRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingBatchStepRequest) Reset() {
	*x = TrainingBatchStepRequest{}
	mi := &file_api_training_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingBatchStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingBatchStepRequest) ProtoMessage() {}

func (x *TrainingBatchStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingBatchStepRequest.ProtoReflect.Descriptor instead.
func (*TrainingBatchStepRequest) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{17}
}

func (x *TrainingBatchStepRequest) GetItems() []*TrainingStepRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type TrainingItemResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*TrainingItemResult_Transition
	//	*TrainingItemResult_Error
	Outcome       isTrainingItemResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingItemResult) Reset() {
	*x = TrainingItemResult{}
	mi := &file_api_training_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingItemResult) ProtoMessage() {}

func (x *TrainingItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingItemResult.ProtoReflect.Descriptor instead.
func (*TrainingItemResult) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{18}
}

func (x *TrainingItemResult) GetOutcome() isTrainingItemResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *TrainingItemResult) GetTransition() *TrainingTransition {
	if x != nil {
		if x, ok := x.Outcome.(*TrainingItemResult_Transition); ok {
			return x.Transition
		}
	}
	return nil
}

func (x *TrainingItemResult) GetError() *APIError {
	if x != nil {
		if x, ok := x.Outcome.(*TrainingItemResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTrainingItemResult_Outcome interface {
	isTrainingItemResult_Outcome()
}

type TrainingItemResult_Transition struct {
	Transition *TrainingTransition `protobuf:"bytes,1,opt,name=transition,proto3,oneof"`
}

type TrainingItemResult_Error struct {
	Error *APIError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*TrainingItemResult_Transition) isTrainingItemResult_Outcome() {}

func (*TrainingItemResult_Error) isTrainingItemResult_Outcome() {}

type TrainingBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TrainingItemResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingBatchResponse) Reset() {
	*x = TrainingBatchResponse{}
	mi := &file_api_training_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingBatchResponse) ProtoMessage() {}

func (x *TrainingBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingBatchResponse.ProtoReflect.Descriptor instead.
func (*TrainingBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{19}
}

func (x *TrainingBatchResponse) GetResults() []*TrainingItemResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TokenBucketConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Capacity              int64                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RefillTokensPerSecond float64                `protobuf:"fixed64,2,opt,name=refill_tokens_per_second,json=refillTokensPerSecond,proto3" json:"refill_tokens_per_second,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TokenBucketConfig) Reset() {
	*x = TokenBucketConfig{}
	mi := &file_api_training_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBucketConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBucketConfig) ProtoMessage() {}

func (x *TokenBucketConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBucketConfig.ProtoReflect.Descriptor instead.
func (*TokenBucketConfig) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{20}
}

func (x *TokenBucketConfig) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *TokenBucketConfig) GetRefillTokensPerSecond() float64 {
	if x != nil {
		return x.RefillTokensPerSecond
	}
	return 0
}

type TrainingKeyRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Bucket        *TokenBucketConfig     `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RevokedAt     string                 `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingKeyRecord) Reset() {
	*x = TrainingKeyRecord{}
	mi := &file_api_training_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingKeyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingKeyRecord) ProtoMessage() {}

func (x *TrainingKeyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingKeyRecord.ProtoReflect.Descriptor instead.
func (*TrainingKeyRecord) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{21}
}

func (x *TrainingKeyRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainingKeyRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingKeyRecord) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *TrainingKeyRecord) GetBucket() *TokenBucketConfig {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *TrainingKeyRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TrainingKeyRecord) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *TrainingKeyRecord) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

type ListTrainingKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*TrainingKeyRecord   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrainingKeysResponse) Reset() {
	*x = ListTrainingKeysResponse{}
	mi := &file_api_training_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrainingKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainingKeysResponse) ProtoMessage() {}

func (x *ListTrainingKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrainingKeysResponse.ProtoReflect.Descriptor instead.
func (*ListTrainingKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{22}
}

func (x *ListTrainingKeysResponse) GetKeys() []*TrainingKeyRecord {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CreateTrainingKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bucket        *TokenBucketConfig     `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrainingKeyRequest) Reset() {
	*x = CreateTrainingKeyRequest{}
	mi := &file_api_training_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrainingKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainingKeyRequest) ProtoMessage() {}

func (x *CreateTrainingKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainingKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateTrainingKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{23}
}

func (x *CreateTrainingKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTrainingKeyRequest) GetBucket() *TokenBucketConfig {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *CreateTrainingKeyRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type CreateTrainingKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *TrainingKeyRecord     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrainingKeyResponse) Reset() {
	*x = CreateTrainingKeyResponse{}
	mi := &file_api_training_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrainingKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainingKeyResponse) ProtoMessage() {}

func (x *CreateTrainingKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainingKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateTrainingKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTrainingKeyResponse) GetKey() *TrainingKeyRecord {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CreateTrainingKeyResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type UpdateTrainingKeyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bucket          *TokenBucketConfig     `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ClearExpiration bool                   `protobuf:"varint,4,opt,name=clear_expiration,json=clearExpiration,proto3" json:"clear_expiration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTrainingKeyRequest) Reset() {
	*x = UpdateTrainingKeyRequest{}
	mi := &file_api_training_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrainingKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainingKeyRequest) ProtoMessage() {}

func (x *UpdateTrainingKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_training_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainingKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrainingKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_training_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateTrainingKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTrainingKeyRequest) GetBucket() *TokenBucketConfig {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *UpdateTrainingKeyRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *UpdateTrainingKeyRequest) GetClearExpiration() bool {
	if x != nil {
		return x.ClearExpiration
	}
	return false
}

var File_api_training_proto protoreflect.FileDescriptor

const file_api_training_proto_rawDesc = "" +
	"\n" +
	"\x12api/training.proto\x12\x11vorax.training.v1\x1a\x0eapi/game.proto\"`\n" +
	"\x0eTrainingAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12!\n" +
	"\ftarget_slots\x18\x03 \x03(\x05R\vtargetSlots\"\xd0\x01\n" +
	"\x17TrainingSlotObservation\x12#\n" +
	"\rdefinition_id\x18\x01 \x01(\tR\fdefinitionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12\x16\n" +
	"\x06family\x18\x04 \x01(\x05R\x06family\x12\x16\n" +
	"\x06rarity\x18\x05 \x01(\x05R\x06rarity\x12\x1a\n" +
	"\bactivity\x18\x06 \x01(\x03R\bactivity\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\"Y\n" +
	"\x18TrainingOfferObservation\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\x12)\n" +
	"\x10reward_threshold\x18\x02 \x01(\x03R\x0frewardThreshold\")\n" +
	"\x11TrainingTargetSet\x12\x14\n" +
	"\x05slots\x18\x01 \x03(\x05R\x05slots\"\xee\x01\n" +
	"\x17TrainingCardObservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\x05R\x04kind\x12\x16\n" +
	"\x06rarity\x18\x05 \x01(\x05R\x06rarity\x12\x1a\n" +
	"\bplayable\x18\x06 \x01(\bR\bplayable\x12E\n" +
	"\vtarget_sets\x18\a \x03(\v2$.vorax.training.v1.TrainingTargetSetR\n" +
	"targetSets\"P\n" +
	"\x18TrainingClaimObservation\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x03R\tthreshold\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xfe\x01\n" +
	"\x19TrainingRewardObservation\x12\x12\n" +
	"\x04jars\x18\x01 \x03(\x05R\x04jars\x12,\n" +
	"\x12drop_bonus_percent\x18\x02 \x01(\x05R\x10dropBonusPercent\x12%\n" +
	"\x0enext_threshold\x18\x03 \x01(\x03R\rnextThreshold\x12*\n" +
	"\x11next_reward_label\x18\x04 \x01(\tR\x0fnextRewardLabel\x12L\n" +
	"\vtool_claims\x18\x05 \x03(\v2+.vorax.training.v1.TrainingClaimObservationR\n" +
	"toolClaims\"\xfe\x04\n" +
	"\x13TrainingObservation\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1f\n" +
	"\vstage_label\x18\x02 \x01(\tR\n" +
	"stageLabel\x12\x1f\n" +
	"\vbase_cursor\x18\x03 \x01(\x05R\n" +
	"baseCursor\x12'\n" +
	"\x0fcompleted_turns\x18\x04 \x01(\x05R\x0ecompletedTurns\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x03R\x05score\x12@\n" +
	"\x05slots\x18\x06 \x03(\v2*.vorax.training.v1.TrainingSlotObservationR\x05slots\x12\x14\n" +
	"\x05tools\x18\a \x03(\tR\x05tools\x12\x1d\n" +
	"\n" +
	"tool_names\x18\b \x03(\tR\ttoolNames\x12A\n" +
	"\x05offer\x18\t \x01(\v2+.vorax.training.v1.TrainingOfferObservationR\x05offer\x12@\n" +
	"\x05cards\x18\n" +
	" \x03(\v2*.vorax.training.v1.TrainingCardObservationR\x05cards\x12\x19\n" +
	"\bcan_skip\x18\v \x01(\bR\acanSkip\x12\x1f\n" +
	"\vcan_refresh\x18\f \x01(\bR\n" +
	"canRefresh\x12)\n" +
	"\x10potion_refreshes\x18\r \x01(\x05R\x0fpotionRefreshes\x12%\n" +
	"\x0etool_refreshes\x18\x0e \x01(\x05R\rtoolRefreshes\x12F\n" +
	"\arewards\x18\x0f \x01(\v2,.vorax.training.v1.TrainingRewardObservationR\arewards\"\xb2\x05\n" +
	"\x11TensorObservation\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\x05R\x05phase\x12\x1a\n" +
	"\bprogress\x18\x02 \x03(\x05R\bprogress\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12#\n" +
	"\rslot_monsters\x18\x04 \x03(\x05R\fslotMonsters\x12#\n" +
	"\rslot_families\x18\x05 \x03(\x05R\fslotFamilies\x12#\n" +
	"\rslot_rarities\x18\x06 \x03(\x05R\fslotRarities\x12'\n" +
	"\x0fslot_activities\x18\a \x03(\x03R\x0eslotActivities\x12'\n" +
	"\x0fslot_quantities\x18\b \x03(\x03R\x0eslotQuantities\x12\x1f\n" +
	"\vtool_counts\x18\t \x03(\x05R\n" +
	"toolCounts\x12\x14\n" +
	"\x05offer\x18\n" +
	" \x03(\x05R\x05offer\x124\n" +
	"\x16offer_reward_threshold\x18\v \x01(\x03R\x14offerRewardThreshold\x12'\n" +
	"\x0fcandidate_cards\x18\f \x03(\x05R\x0ecandidateCards\x12-\n" +
	"\x12candidate_playable\x18\r \x03(\x05R\x11candidatePlayable\x12\x1c\n" +
	"\trefreshes\x18\x0e \x03(\x05R\trefreshes\x12\x1f\n" +
	"\vreward_jars\x18\x0f \x03(\x05R\n" +
	"rewardJars\x12,\n" +
	"\x12drop_bonus_percent\x18\x10 \x01(\x05R\x10dropBonusPercent\x12.\n" +
	"\x13tool_claim_statuses\x18\x11 \x03(\x05R\x11toolClaimStatuses\x122\n" +
	"\x15next_reward_threshold\x18\x12 \x01(\x03R\x13nextRewardThreshold\"\xb6\x01\n" +
	"\fTrainingInfo\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x03R\x05score\x12#\n" +
	"\rrules_version\x18\x02 \x01(\tR\frulesVersion\x12'\n" +
	"\x0fcontent_version\x18\x03 \x01(\tR\x0econtentVersion\x12\x1f\n" +
	"\vrng_version\x18\x04 \x01(\tR\n" +
	"rngVersion\x12!\n" +
	"\fspec_version\x18\x05 \x01(\tR\vspecVersion\"\xcc\x03\n" +
	"\x12TrainingTransition\x12#\n" +
	"\repisode_token\x18\x01 \x01(\tR\fepisodeToken\x12H\n" +
	"\vobservation\x18\x02 \x01(\v2&.vorax.training.v1.TrainingObservationR\vobservation\x12S\n" +
	"\x12tensor_observation\x18\x03 \x01(\v2$.vorax.training.v1.TensorObservationR\x11tensorObservation\x12F\n" +
	"\rlegal_actions\x18\x04 \x03(\v2!.vorax.training.v1.TrainingActionR\flegalActions\x12\x1f\n" +
	"\vaction_mask\x18\x05 \x03(\x05R\n" +
	"actionMask\x12\x16\n" +
	"\x06reward\x18\x06 \x01(\x03R\x06reward\x12\x1e\n" +
	"\n" +
	"terminated\x18\a \x01(\bR\n" +
	"terminated\x12\x1c\n" +
	"\ttruncated\x18\b \x01(\bR\ttruncated\x123\n" +
	"\x04info\x18\t \x01(\v2\x1f.vorax.training.v1.TrainingInfoR\x04info\"e\n" +
	"\x12TrainingActionSpec\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x129\n" +
	"\x06action\x18\x02 \x01(\v2!.vorax.training.v1.TrainingActionR\x06action\"\xc9\x01\n" +
	"\x12TrainingTensorSpec\x12\x1d\n" +
	"\n" +
	"slot_count\x18\x01 \x01(\x05R\tslotCount\x12'\n" +
	"\x0fcandidate_count\x18\x02 \x01(\x05R\x0ecandidateCount\x12\x1d\n" +
	"\n" +
	"tool_count\x18\x03 \x01(\x05R\ttoolCount\x12!\n" +
	"\faction_count\x18\x04 \x01(\x05R\vactionCount\x12)\n" +
	"\x10integer_encoding\x18\x05 \x01(\tR\x0fintegerEncoding\"\x94\x03\n" +
	"\fTrainingSpec\x12!\n" +
	"\fspec_version\x18\x01 \x01(\tR\vspecVersion\x12\x1b\n" +
	"\tspec_hash\x18\x02 \x01(\tR\bspecHash\x12#\n" +
	"\rrules_version\x18\x03 \x01(\tR\frulesVersion\x12'\n" +
	"\x0fcontent_version\x18\x04 \x01(\tR\x0econtentVersion\x12\x1f\n" +
	"\vrng_version\x18\x05 \x01(\tR\n" +
	"rngVersion\x12\x1f\n" +
	"\vmonster_ids\x18\x06 \x03(\tR\n" +
	"monsterIds\x12\x19\n" +
	"\bcard_ids\x18\a \x03(\tR\acardIds\x12\x19\n" +
	"\btool_ids\x18\b \x03(\tR\atoolIds\x12?\n" +
	"\aactions\x18\t \x03(\v2%.vorax.training.v1.TrainingActionSpecR\aactions\x12=\n" +
	"\x06tensor\x18\n" +
	" \x01(\v2%.vorax.training.v1.TrainingTensorSpecR\x06tensor\"O\n" +
	"\x14TrainingResetRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\tR\x04seed\x12#\n" +
	"\rpet_refreshes\x18\x02 \x01(\x05R\fpetRefreshes\"\xaf\x01\n" +
	"\x13TrainingStepRequest\x12#\n" +
	"\repisode_token\x18\x01 \x01(\tR\fepisodeToken\x12#\n" +
	"\faction_index\x18\x02 \x01(\x05H\x00R\vactionIndex\x12;\n" +
	"\x06action\x18\x03 \x01(\v2!.vorax.training.v1.TrainingActionH\x00R\x06actionB\x11\n" +
	"\x0fselected_action\"Z\n" +
	"\x19TrainingBatchResetRequest\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.vorax.training.v1.TrainingResetRequestR\x05items\"X\n" +
	"\x18TrainingBatchStepRequest\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.vorax.training.v1.TrainingStepRequestR\x05items\"\x94\x01\n" +
	"\x12TrainingItemResult\x12G\n" +
	"\n" +
	"transition\x18\x01 \x01(\v2%.vorax.training.v1.TrainingTransitionH\x00R\n" +
	"transition\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.vorax.v1.APIErrorH\x00R\x05errorB\t\n" +
	"\aoutcome\"X\n" +
	"\x15TrainingBatchResponse\x12?\n" +
	"\aresults\x18\x01 \x03(\v2%.vorax.training.v1.TrainingItemResultR\aresults\"h\n" +
	"\x11TokenBucketConfig\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x03R\bcapacity\x127\n" +
	"\x18refill_tokens_per_second\x18\x02 \x01(\x01R\x15refillTokensPerSecond\"\xea\x01\n" +
	"\x11TrainingKeyRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12<\n" +
	"\x06bucket\x18\x04 \x01(\v2$.vorax.training.v1.TokenBucketConfigR\x06bucket\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\a \x01(\tR\trevokedAt\"T\n" +
	"\x18ListTrainingKeysResponse\x128\n" +
	"\x04keys\x18\x01 \x03(\v2$.vorax.training.v1.TrainingKeyRecordR\x04keys\"\x8b\x01\n" +
	"\x18CreateTrainingKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x06bucket\x18\x02 \x01(\v2$.vorax.training.v1.TokenBucketConfigR\x06bucket\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"k\n" +
	"\x19CreateTrainingKeyResponse\x126\n" +
	"\x03key\x18\x01 \x01(\v2$.vorax.training.v1.TrainingKeyRecordR\x03key\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\xb6\x01\n" +
	"\x18UpdateTrainingKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x06bucket\x18\x02 \x01(\v2$.vorax.training.v1.TokenBucketConfigR\x06bucket\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12)\n" +
	"\x10clear_expiration\x18\x04 \x01(\bR\x0fclearExpirationB\"Z vorax/internal/protocol;protocolb\x06proto3"

var (
	file_api_training_proto_rawDescOnce sync.Once
	file_api_training_proto_rawDescData []byte
)

func file_api_training_proto_rawDescGZIP() []byte {
	file_api_training_proto_rawDescOnce.Do(func() {
		file_api_training_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_training_proto_rawDesc), len(file_api_training_proto_rawDesc)))
	})
	return file_api_training_proto_rawDescData
}

var file_api_training_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_training_proto_goTypes = []any{
	(*TrainingAction)(nil),            // 0: vorax.training.v1.TrainingAction
	(*TrainingSlotObservation)(nil),   // 1: vorax.training.v1.TrainingSlotObservation
	(*TrainingOfferObservation)(nil),  // 2: vorax.training.v1.TrainingOfferObservation
	(*TrainingTargetSet)(nil),         // 3: vorax.training.v1.TrainingTargetSet
	(*TrainingCardObservation)(nil),   // 4: vorax.training.v1.TrainingCardObservation
	(*TrainingClaimObservation)(nil),  // 5: vorax.training.v1.TrainingClaimObservation
	(*TrainingRewardObservation)(nil), // 6: vorax.training.v1.TrainingRewardObservation
	(*TrainingObservation)(nil),       // 7: vorax.training.v1.TrainingObservation
	(*TensorObservation)(nil),         // 8: vorax.training.v1.TensorObservation
	(*TrainingInfo)(nil),              // 9: vorax.training.v1.TrainingInfo
	(*TrainingTransition)(nil),        // 10: vorax.training.v1.TrainingTransition
	(*TrainingActionSpec)(nil),        // 11: vorax.training.v1.TrainingActionSpec
	(*TrainingTensorSpec)(nil),        // 12: vorax.training.v1.TrainingTensorSpec
	(*TrainingSpec)(nil),              // 13: vorax.training.v1.TrainingSpec
	(*TrainingResetRequest)(nil),      // 14: vorax.training.v1.TrainingResetRequest
	(*TrainingStepRequest)(nil),       // 15: vorax.training.v1.TrainingStepRequest
	(*TrainingBatchResetRequest)(nil), // 16: vorax.training.v1.TrainingBatchResetRequest
	(*TrainingBatchStepRequest)(nil),  // 17: vorax.training.v1.TrainingBatchStepRequest
	(*TrainingItemResult)(nil),        // 18: vorax.training.v1.TrainingItemResult
	(*TrainingBatchResponse)(nil),     // 19: vorax.training.v1.TrainingBatchResponse
	(*TokenBucketConfig)(nil),         // 20: vorax.training.v1.TokenBucketConfig
	(*TrainingKeyRecord)(nil),         // 21: vorax.training.v1.TrainingKeyRecord
	(*ListTrainingKeysResponse)(nil),  // 22: vorax.training.v1.ListTrainingKeysResponse
	(*CreateTrainingKeyRequest)(nil),  // 23: vorax.training.v1.CreateTrainingKeyRequest
	(*CreateTrainingKeyResponse)(nil), // 24: vorax.training.v1.CreateTrainingKeyResponse
	(*UpdateTrainingKeyRequest)(nil),  // 25: vorax.training.v1.UpdateTrainingKeyRequest
	(*APIError)(nil),                  // 26: vorax.v1.APIError
}
var file_api_training_proto_depIdxs = []int32{
	3,  // 0: vorax.training.v1.TrainingCardObservation.target_sets:type_name -> vorax.training.v1.TrainingTargetSet
	5,  // 1: vorax.training.v1.TrainingRewardObservation.tool_claims:type_name -> vorax.training.v1.TrainingClaimObservation
	1,  // 2: vorax.training.v1.TrainingObservation.slots:type_name -> vorax.training.v1.TrainingSlotObservation
	2,  // 3: vorax.training.v1.TrainingObservation.offer:type_name -> vorax.training.v1.TrainingOfferObservation
	4,  // 4: vorax.training.v1.TrainingObservation.cards:type_name -> vorax.training.v1.TrainingCardObservation
	6,  // 5: vorax.training.v1.TrainingObservation.rewards:type_name -> vorax.training.v1.TrainingRewardObservation
	7,  // 6: vorax.training.v1.TrainingTransition.observation:type_name -> vorax.training.v1.TrainingObservation
	8,  // 7: vorax.training.v1.TrainingTransition.tensor_observation:type_name -> vorax.training.v1.TensorObservation
	0,  // 8: vorax.training.v1.TrainingTransition.legal_actions:type_name -> vorax.training.v1.TrainingAction
	9,  // 9: vorax.training.v1.TrainingTransition.info:type_name -> vorax.training.v1.TrainingInfo
	0,  // 10: vorax.training.v1.TrainingActionSpec.action:type_name -> vorax.training.v1.TrainingAction
	11, // 11: vorax.training.v1.TrainingSpec.actions:type_name -> vorax.training.v1.TrainingActionSpec
	12, // 12: vorax.training.v1.TrainingSpec.tensor:type_name -> vorax.training.v1.TrainingTensorSpec
	0,  // 13: vorax.training.v1.TrainingStepRequest.action:type_name -> vorax.training.v1.TrainingAction
	14, // 14: vorax.training.v1.TrainingBatchResetRequest.items:type_name -> vorax.training.v1.TrainingResetRequest
	15, // 15: vorax.training.v1.TrainingBatchStepRequest.items:type_name -> vorax.training.v1.TrainingStepRequest
	10, // 16: vorax.training.v1.TrainingItemResult.transition:type_name -> vorax.training.v1.TrainingTransition
	26, // 17: vorax.training.v1.TrainingItemResult.error:type_name -> vorax.v1.APIError
	18, // 18: vorax.training.v1.TrainingBatchResponse.results:type_name -> vorax.training.v1.TrainingItemResult
	20, // 19: vorax.training.v1.TrainingKeyRecord.bucket:type_name -> vorax.training.v1.TokenBucketConfig
	21, // 20: vorax.training.v1.ListTrainingKeysResponse.keys:type_name -> vorax.training.v1.TrainingKeyRecord
	20, // 21: vorax.training.v1.CreateTrainingKeyRequest.bucket:type_name -> vorax.training.v1.TokenBucketConfig
	21, // 22: vorax.training.v1.CreateTrainingKeyResponse.key:type_name -> vorax.training.v1.TrainingKeyRecord
	20, // 23: vorax.training.v1.UpdateTrainingKeyRequest.bucket:type_name -> vorax.training.v1.TokenBucketConfig
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_training_proto_init() }
func file_api_training_proto_init() {
	if File_api_training_proto != nil {
		return
	}
	file_api_game_proto_init()
	file_api_training_proto_msgTypes[15].OneofWrappers = []any{
		(*TrainingStepRequest_ActionIndex)(nil),
		(*TrainingStepRequest_Action)(nil),
	}
	file_api_training_proto_msgTypes[18].OneofWrappers = []any{
		(*TrainingItemResult_Transition)(nil),
		(*TrainingItemResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_training_proto_rawDesc), len(file_api_training_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_training_proto_goTypes,
		DependencyIndexes: file_api_training_proto_depIdxs,
		MessageInfos:      file_api_training_proto_msgTypes,
	}.Build()
	File_api_training_proto = out.File
	file_api_training_proto_goTypes = nil
	file_api_training_proto_depIdxs = nil
}
